Name: ex3 - Flow over a hump

Total Length (in meter) for each reach:
8.0
4.0
13.0

Discretization: number of cells per reach:
1280
640
2080

Geometry of the each reach: Straight or Formulated reach (0: means a straight reach, 1: means a Formulated)
0
1
0

Slope for each reach 
0.0e-00
0.0e-00
0.0e-00

Manning's number for each slope:
0.00
0.00
0.00

Cross section widths of each slope (in meter, assumed to be rectangular for now):
1
1
1
