Name: ex2 - Flow over a hump with shock

Total Length (in meter) for each reach:
200.0

Discretization: number of cells per reach:
400

Geometry of the each reach: Straight or Formulated reach (0: means a straight reach, 1: means a Formulated)
0

Slope for each reach 
0.0

Manning's number for each slope:
0.0

Cross section widths of each slope (in meter, assumed to be rectangular for now):
4.0



